### PR TITLE
Submit secure email docs under new PR.

### PR DESCRIPTION
**Pull request by laschultz**

### CODE REVIEW

**Comment by bennage** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-toc?branch=pr-en-us-151) | [Details](#user-content-docs%2Fbest-practices%2Femail-toc.md)
[docs/best-practices/email-deploy-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-deploy-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/email-ems-office365-service-descriptions.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-ems-office365-service-descriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-ems-office365-service-descriptions?branch=pr-en-us-151) |
[docs/best-practices/email-introduction.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-introduction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/email-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/baseline-ca-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/baseline-ca-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/exchange-online-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/exchange-online-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/intune-mobile-app-mgmt.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/intune-mobile-app-mgmt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/security-triad.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/security-triad.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/images/email/typical-authentication-flow.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/typical-authentication-flow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |

<a name="docs%2Fbest-practices%2Femail-toc.md"></a>
### [docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md)
 - **[Warning]** Failed to find Git account for the committer v-logoff@microsoft.com. Solution: 1) File creator to associate email address v-logoff@microsoft.com with his or her Git account, or 2) Anyone to explicitly add &quot;author: &lt;Git account&gt;&quot; into markdown YAML header.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201705301754401887-151%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-toc?branch=pr-en-us-151) | [Details](#user-content-docs%2Fbest-practices%2Femail-toc.md)
[docs/best-practices/email-deploy-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-deploy-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/email-ems-office365-service-descriptions.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-ems-office365-service-descriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-ems-office365-service-descriptions?branch=pr-en-us-151) |
[docs/best-practices/email-introduction.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-introduction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/email-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/baseline-ca-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/baseline-ca-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/exchange-online-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/exchange-online-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/intune-mobile-app-mgmt.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/intune-mobile-app-mgmt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/security-triad.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/security-triad.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/images/email/typical-authentication-flow.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/typical-authentication-flow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |

<a name="docs%2Fbest-practices%2Femail-toc.md"></a>
### [docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md)
 - **[Warning]** Failed to find Git account for the committer v-logoff@microsoft.com. Solution: 1) File creator to associate email address v-logoff@microsoft.com with his or her Git account, or 2) Anyone to explicitly add &quot;author: &lt;Git account&gt;&quot; into markdown YAML header.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201705301907561373-151%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-toc?branch=pr-en-us-151) | [Details](#user-content-docs%2Fbest-practices%2Femail-toc.md)
[docs/best-practices/email-deploy-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-deploy-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/email-ems-office365-service-descriptions.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-ems-office365-service-descriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-ems-office365-service-descriptions?branch=pr-en-us-151) |
[docs/best-practices/email-introduction.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-introduction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/email-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/baseline-ca-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/baseline-ca-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/exchange-online-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/exchange-online-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/intune-mobile-app-mgmt.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/intune-mobile-app-mgmt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/security-triad.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/security-triad.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/images/email/typical-authentication-flow.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/typical-authentication-flow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |

<a name="docs%2Fbest-practices%2Femail-toc.md"></a>
### [docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md)
 - **[Warning]** Failed to find Git account for the committer v-logoff@microsoft.com. Solution: 1) File creator to associate email address v-logoff@microsoft.com with his or her Git account, or 2) Anyone to explicitly add &quot;author: &lt;Git account&gt;&quot; into markdown YAML header.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201705301912506562-151%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-toc?branch=pr-en-us-151) | [Details](#user-content-docs%2Fbest-practices%2Femail-toc.md)
[docs/best-practices/email-deploy-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-deploy-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/email-ems-office365-service-descriptions.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-ems-office365-service-descriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-ems-office365-service-descriptions?branch=pr-en-us-151) |
[docs/best-practices/email-introduction.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-introduction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/email-recommended-policies.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-recommended-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/baseline-ca-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/baseline-ca-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/exchange-online-policy.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/exchange-online-policy.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/intune-mobile-app-mgmt.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/intune-mobile-app-mgmt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-deploy-recommended-policies?branch=pr-en-us-151) |
[docs/best-practices/images/email/security-triad.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/security-triad.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |
[docs/best-practices/images/email/typical-authentication-flow.png](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/images/email/typical-authentication-flow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/email-introduction?branch=pr-en-us-151) |

<a name="docs%2Fbest-practices%2Femail-toc.md"></a>
### [docs/best-practices/email-toc.md](https://github.com/laschultz/architecture-center/blob/master/docs/best-practices/email-toc.md)
 - **[Warning]** Failed to find Git account for the committer v-logoff@microsoft.com. Solution: 1) File creator to associate email address v-logoff@microsoft.com with his or her Git account, or 2) Anyone to explicitly add &quot;author: &lt;Git account&gt;&quot; into markdown YAML header.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C2%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706021515522590-151%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by laschultz** [comment]
Move to azure-docs-pr

**Pull request closed without merging**
