### PR TITLE
removed xtra CRLF; added Prereqs; rev'd deploy steps

### PR DESCRIPTION
**Pull request by njray**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sap/index.md](https://github.com/njray/architecture-center/blob/larry/sap/docs/reference-architectures/sap/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/index?branch=pr-en-us-179) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C24%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706241635466585-179%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lbrader** [comment]
@MikeWasson I sync with Nanette - the only thing that may change are some name changes for the SKU and VM names.  I'll close that today.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sap/index.md](https://github.com/njray/architecture-center/blob/larry/sap/docs/reference-architectures/sap/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/index?branch=pr-en-us-179) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706291955586902-179%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sap/index.md](https://github.com/njray/architecture-center/blob/larry/sap/docs/reference-architectures/sap/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/index?branch=pr-en-us-179) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706292007550291-179%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
