### PR TITLE
C-Card Alt Tags & Accessibility: removed alt contents

### PR DESCRIPTION
**Pull request by cmcclister**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/cmcclister/architecture-center/blob/1201194/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/index?branch=pr-en-us-461) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C20%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201803201548491262-461%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lMGsqrO6S4MP115UnIAz4Y6UjoSUhMxED8eYvh75Rdo%3D&st=2018-03-20T15%3A45%3A19Z&se=2018-04-20T15%3A50%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by cmcclister** [comment]
#sign-off apexprod

**Comment by MikeWasson** [comment]
@cmcclister Hi - What is the reason for remove the alt text?

**Comment by bennage** [comment]
@cmcclister Can you connect to the originator of this request?

**Comment by DuncanmaMSFT** [comment]
FYI, I believe the ALT text is being removed because it is duplicated in the text that follows, so the user experience to a screen reader user is to say the same text twice in a row. @cmcclister should be able to explain where the request came in though.

**Comment by cmcclister** [comment]
@MikeWasson @bennage @DuncanmaMSFT alt tags with values are breaking accessibility when used in the C-Cards, per @adkinn

**Comment by MikeWasson** [comment]
OK, thanks!

**Pull request merged**
