### PR TITLE
changes to hub-spoke and add sss

### PR DESCRIPTION
**Pull request by telmosampaio**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/hub-spoke.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/shared-securiity-stack.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/shared-securiity-stack.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-securiity-stack?branch=pr-en-us-426) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802260703454107-426%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SuTOk6WAOb2r6wpK1kjpj5ygIzgDWeuwdWGZNpnbitQ%3D&st=2018-02-26T06%3A59%3A38Z&se=2018-03-29T07%3A04%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
@telmosampaio Since this is a change to a different content set than ACAG, consider using a separate branch, so we can review / publish it independently?

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/hub-spoke.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/images/hub-spoke.png](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/images/hub-spoke.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/images/shared-services.png](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/images/shared-services.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/shared-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?branch=pr-en-us-426) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802261749145167-426%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kITsPvxiRAmraYjKca9eVEuoEIoC8U6nA%2BDv%2BgvwcZU%3D&st=2018-02-26T17%3A45%3A08Z&se=2018-03-29T17%3A50%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/hub-spoke.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/images/hub-spoke.png](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/images/hub-spoke.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/images/shared-services.png](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/images/shared-services.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/shared-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?branch=pr-en-us-426) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C28%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802281525100106-426%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9mA7hZVp3SDuoM0NjvkeQgVXAVaJo8zF0OxbBJGomZ0%3D&st=2018-02-28T15%3A21%3A36Z&se=2018-03-31T15%3A26%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/hub-spoke.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/images/hub-spoke.png](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/images/hub-spoke.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/images/shared-services.png](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/images/shared-services.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?branch=pr-en-us-426) |
[docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/mspnp/architecture-center/blob/telmos/acag-intermediate-working/docs/reference-architectures/hybrid-networking/shared-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?branch=pr-en-us-426) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C2%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201803020109171539-426%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m%2FU6p%2F0xMG9f3%2FheGfn96NQMI%2F8mki9Ed8irqeRZhEY%3D&st=2018-03-02T01%3A05%3A17Z&se=2018-04-02T01%3A10%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by telmosampaio** [comment]
This PR was substituted by https://github.com/mspnp/architecture-center/pull/437

**Pull request closed without merging**
