### PR TITLE
Update CDN best practices article

### PR DESCRIPTION
**Pull request by MikeWasson**
Update to remove information that is specific to Azure CDN service

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/mspnp/architecture-center/blob/mike/cdn/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-382) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802012300404042-382%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GUXxMi08Lveni9y4HFxlpKgTPUiBLiO4WlxA2CwNNaM%3D&st=2018-02-01T22%3A56%3A37Z&se=2018-03-04T23%3A01%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
@dksimpson @lichard

**Comment by Lichard** [comment]
Looks good to me.

**Comment by dksimpson** [comment]
Looks good.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/mspnp/architecture-center/blob/mike/cdn/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-382) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C3%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802030338133390-382%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XAh%2Bu59EznIc2j573%2FjEJSZtvBOydfeF95iyFwukiCU%3D&st=2018-02-03T03%3A34%3A13Z&se=2018-03-06T03%3A39%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
