### PR TITLE
Update default value and explanation for MaximumExecutionTime

### PR DESCRIPTION
**Pull request by zezha-msft**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/retry-service-specific.md](https://github.com/zezha-msft/architecture-center/blob/patch-1/docs/best-practices/retry-service-specific.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific?branch=pr-en-us-539) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C18%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201805180634197393-539%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DbigOmBccAyLpaMj409SoVx09BSh8pIVg8x%2Fewbs4uk%3D&st=2018-05-18T06%3A30%3A32Z&se=2018-06-18T06%3A35%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zezha-msft** [comment]
Hi @MikeWasson, could you please review/merge this change?

My manager @mirobers has approved.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/retry-service-specific.md](https://github.com/zezha-msft/architecture-center/blob/patch-1/docs/best-practices/retry-service-specific.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific?branch=pr-en-us-539) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C21%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201805211650519528-539%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ofMDDW%2BxRN%2BoEZyRfpBHaUYKpun82zfItiAD%2FcwFJWQ%3D&st=2018-05-21T16%3A46%3A53Z&se=2018-06-21T16%3A51%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zezha-msft** [comment]
Thanks @MikeWasson!

**Pull request merged**
