### PR TITLE
Added custom attribute for tracking contributions.

### PR DESCRIPTION
**Pull request by adamboeglin**

### CODE REVIEW

**Comment by MikeWasson** [comment]
@adamboeglin Is it OK if I piggy back on this PR?

**Comment by adamboeglin** [comment]
> 
> 
> @adamboeglin Is it OK if I piggy back on this PR?

Go for it

**Comment by MikeWasson** [comment]
@adamboeglin Based on David's suggestion, I used `azcat-ai` for the AzureCAT AI team. The idea is we could filter on `azcat*` or `azcat-ai`. You have `cat-team`, I guess we should align in one direction or the other. I don't have a strong preference 😃

**Comment by adamboeglin** [comment]
@MikeWasson, that works for me.  Mine wasn't from a specific team in cat, so I'll just use azcat.

**Pull request merged**
