### PR TITLE
Added Azure DNS to 3 web app RAs and the single VM RA.

### PR DESCRIPTION
**Pull request by alexbuckgit**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/basic-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/basic-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/basic-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/scalable-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/scalable-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712121923106046-327%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wCCNFAT949VPJF8Uvgs%2Fz%2FK8fI%2BDMShNp6ecxcYr83k%3D&st=2017-12-12T19%3A19%3A11Z&se=2018-01-12T19%3A24%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/basic-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/basic-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/basic-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/scalable-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/scalable-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712122028064528-327%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=v26p9TxDff8f47A4dNduLzepqPWpYgZyxbc1OY3eIns%3D&st=2017-12-12T20%3A24%3A06Z&se=2018-01-12T20%3A29%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/basic-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/basic-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/basic-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/scalable-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/scalable-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712122030283844-327%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iVhRZvw7nJw6DTyyXBYeSTsKReVWrtttLdtPws2NREU%3D&st=2017-12-12T20%3A26%3A25Z&se=2018-01-12T20%3A31%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/basic-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/basic-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/basic-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/scalable-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/scalable-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712122036173962-327%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Q7iP1KqsuONmEgebgTW%2F1vkhRZLkh9I3zsl2QOLlrHQ%3D&st=2017-12-12T20%3A32%3A14Z&se=2018-01-12T20%3A37%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/basic-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/basic-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/basic-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/scalable-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/scalable-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.svg](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712122054548482-327%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8b9qwCIGeVlKhRJ%2F%2BBSif3ZP5sXHCZzPWbNtyxYXkzw%3D&st=2017-12-12T20%3A50%3A50Z&se=2018-01-12T20%3A55%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
for basic web app, can we tighten the diagram in the vertical direction (move AAD down and DNS up) - right now it's pushing the 1st H2 down the page. Or maybe just scale the diagram smaller?

Also - is the drop shadow on Internet and DNS icons intentional?

**Comment by MikeWasson** [comment]
Windows VM - need to crop white space from diagram. Otherwise looks good!

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/basic-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/basic-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/basic-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/multi-region-web-app-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?branch=pr-en-us-327) |
[docs/reference-architectures/app-service-web-app/images/scalable-web-app.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/app-service-web-app/images/scalable-web-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-linux/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-linux/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-linux/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/images/single-vm-diagram.png?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.svg](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/images/single-vm-diagram.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |
[docs/reference-architectures/virtual-machines-windows/single-vm.md](https://github.com/mspnp/architecture-center/blob/alex-dns/docs/reference-architectures/virtual-machines-windows/single-vm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/single-vm?branch=pr-en-us-327) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712122133379390-327%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jvlTReYe2RJ98PukorKnSIf8P1Ym5OE6t2oMrWX0N6g%3D&st=2017-12-12T21%3A29%3A29Z&se=2018-01-12T21%3A34%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
