### PR TITLE
Corrects minor spelling mistake and fixes broken link

### PR DESCRIPTION
**Pull request by c0g1t8**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/patterns/queue-based-load-leveling.md](https://github.com/c0g1t8/architecture-center/blob/master/docs/patterns/queue-based-load-leveling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling?branch=pr-en-us-309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C28%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201711282006408481-309%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EwUizcHaFiqWb29894%2BFY63tq5dfx3aBASnRnTnF1gY%3D&st=2017-11-28T20%3A02%3A44Z&se=2017-12-29T20%3A07%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
Good catch, thanks! 😸

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/patterns/compensating-transaction.md](https://github.com/c0g1t8/architecture-center/blob/master/docs/patterns/compensating-transaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction?branch=pr-en-us-309) |
[docs/patterns/queue-based-load-leveling.md](https://github.com/c0g1t8/architecture-center/blob/master/docs/patterns/queue-based-load-leveling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling?branch=pr-en-us-309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201711290149303759-309%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=J9p5dgWdkfLp1HMNCdCSLkSa2wlQxei2HZIR%2BzCssDI%3D&st=2017-11-29T01%3A45%3A31Z&se=2017-12-30T01%3A50%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by c0g1t8** [comment]
Found a broken link.  Added fix as part of this PR.

**Pull request merged**
