### PR TITLE
Adding a section about Microsoft Defender for Cloud

### PR DESCRIPTION
**Pull request by LianaT**
Microsoft Defender for Cloud has been investing heavily in multi-cloud capabilities. At Ignite, the new AWS connector was launched, and we want to make sure to highlight these multi-cloud capabilities in this article.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@LianaT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger13** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Ed-Price — APPROVED** [review]
Looks good.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger5** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @dougkl007, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
