### PR TITLE
Peter/acag edit

### PR DESCRIPTION
**Pull request by Petertaylor9999**
@bennage  - there's a problem with nested ordered lists in OPS. I had to switch the nested ordered list to unordered.

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/intermediate-stage/overview.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/intermediate-stage/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/overview?branch=pr-en-us-573) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C11%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806112228565143-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wB%2BNnXAt7dibL54MEAnrPsGpWV%2Ba4UCWmr54pZJtv5Y%3D&st=2018-06-11T22%3A24%3A58Z&se=2018-07-12T22%3A29%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
There's a indention issue with the:
- Workload contributor:

**Comment by Petertaylor9999** [comment]
I did that way because the workload contributor is subordinate to the workload owner - but we can put them at the same level if you find it confusing.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/intermediate-stage/overview.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/intermediate-stage/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/overview?branch=pr-en-us-573) |
[docs/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/resources/diagrams?branch=pr-en-us-573) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C18%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806182058336159-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=X%2BoXq9OiUYebi1cbUPh9B%2FRuHQ1SinS8VN3e9DjF0OQ%3D&st=2018-06-18T20%3A54%3A53Z&se=2018-07-19T20%3A59%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/intermediate-stage/overview.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/intermediate-stage/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/overview?branch=pr-en-us-573) |
[docs/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/resources/diagrams?branch=pr-en-us-573) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C18%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806182103174223-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZWa9pz6cSy0sT011Y50EL4RWyUC5qVEmAQy4ah2IUdI%3D&st=2018-06-18T20%3A59%3A29Z&se=2018-07-19T21%3A04%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/intermediate-stage/overview.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/intermediate-stage/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/overview?branch=pr-en-us-573) |
[docs/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/resources/diagrams?branch=pr-en-us-573) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C18%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806182106306098-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vBS2KyVwmzMMw0SkyETlGA%2F853jnsHxtivpsfoCPdcA%3D&st=2018-06-18T21%3A02%3A41Z&se=2018-07-19T21%3A07%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-573) |
[docs/cloud-adoption-guide/intermediate-stage/overview.md](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/cloud-adoption-guide/intermediate-stage/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/overview?branch=pr-en-us-573) |
[docs/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/acag-edit/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/resources/diagrams?branch=pr-en-us-573) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C19%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806190509438553-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8l1BelBwQ%2FtZ%2BNo9y9UQ3xCGsUt8IfZ%2FHF1Gl%2BbAgGg%3D&st=2018-06-19T05%3A05%3A48Z&se=2018-07-20T05%3A10%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
