### PR TITLE
task 625: Improve CDN SEO rank by linking to CDN overview

### PR DESCRIPTION
**Pull request by dksimpson**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/dksimpson/architecture-center/blob/dean-625/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-363) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801122352408143-363%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=M8PYqzqAyyq%2B7pS3Z50uYBWh6ekPNgEFedkKuIXmdAE%3D&st=2018-01-12T23%3A48%3A40Z&se=2018-02-12T23%3A53%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dksimpson** [comment]
#sign-off

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/dksimpson/architecture-center/blob/dean-625/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-363) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C27%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801271726353520-363%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1%2BYFfZiHrTe2lWvrfWWyX0xxyMwwRskVqCS3OKC9%2BQo%3D&st=2018-01-27T17%3A22%3A34Z&se=2018-02-27T17%3A27%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/dksimpson/architecture-center/blob/dean-625/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-363) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C27%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801271729099826-363%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YaLmlVvMQmITZoIPywgoREbkYsdJRSxSRL%2B%2Bh4r0a18%3D&st=2018-01-27T17%3A25%3A08Z&se=2018-02-27T17%3A30%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
