### PR TITLE
clarified allowed Unicode for resource group name

### LINKED ISSUE #863: Resource Group names: not all Unicode characters are supported
For naming of Resource Groups, Valid characters are given as "Alphanumeric, underscore, parentheses, hyphen, period (except at end), and **Unicode characters**". However, not all Unicode characters are supported. For instance, "$" is not supported, and neither are emojis such as "🍦" (U+1F366), while other Unicode characters, such as Chinese characters are. The documentation should be more specific about what ranges of Unicode characters are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

### PR DESCRIPTION
**Pull request by tfitzmac**
Fixes #863

### CODE REVIEW

**Comment by tfitzmac** [comment]
#sign-off

**Comment by MikeWasson** [comment]
Thanks @tfitzmac. What does "that evaluate to an allowed character" mean? Evaluates to alphanumeric, underscore, parentheses, hyphen, or period?

**Comment by tfitzmac** [comment]
Yes, that's the intention. We got feedback form customers that some Unicode characters (like 医掌管) worked but other Unicode characters (like ①②③) didn't work. Characters that don't pass the regex expression failed.

**Comment by lagalbra** [comment]
@tfitzmac Out of curiosity, what is the regex expression you mentioned in your comment above? I'm not aware of a regular expression that would match on Unicode characters like 医掌管.

**Comment by tfitzmac** [comment]
The regex is ^[-\w\._\(\)]+$
Which is listed in the [Resource Groups - Create](https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/createorupdate) REST doc

**Pull request merged**
