### PR TITLE
Update data partitioning for storage

### PR DESCRIPTION
**Pull request by MichaelHauss**
#sign-off

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/data-partitioning.md](https://github.com/MichaelHauss/architecture-center/blob/patch-1/docs/best-practices/data-partitioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning?branch=pr-en-us-154) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C31%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201705312141030932-154%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dragon119** [comment]
Thank you @MichaelHauss for the contribution. Regarding the partitioning Azure blob, my understanding is that each blob has its own partition, correct?

**Comment by MichaelHauss** [comment]
@dragon119 No, that is not correct.

**Comment by dragon119** [comment]
OK, I should have said if load on the blob demands it. Anyway, I want to articulate that point in this doc. Can you add the following to that section?

Each blob can have its own partition if load on the blob demands it.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/data-partitioning.md](https://github.com/MichaelHauss/architecture-center/blob/patch-1/docs/best-practices/data-partitioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning?branch=pr-en-us-154) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C31%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201705312210493540-154%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MichaelHauss** [comment]
Updated.

**Comment by dragon119** [comment]
#sign-off

**Pull request merged**
