### PR TITLE
Sharepoint RA

### PR DESCRIPTION
**Pull request by MikeWasson**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C19%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706191944383496-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706292122312271-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706292125384371-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706292207163742-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706292211179032-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C29%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201706292213383953-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201707121756570148-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lbrader** [comment]
@MikeWasson I think the only thing we need are the links to RA deployment.
https://github.com/mspnp/reference-architectures/tree/master/sharepoint/sharepoint-2016

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/sharepoint/images/sharepoint-ha.png](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/images/sharepoint-ha.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |
[docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/sharepoint-ra/docs/reference-architectures/sharepoint/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/index?branch=pr-en-us-171) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C1%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201708011700050788-171%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
