### PR TITLE
1199282 - ms.topic

### PR DESCRIPTION
**Pull request by cmcclister**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/cmcclister/architecture-center/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/index?branch=pr-en-us-443) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C5%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201803051946502278-443%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a4RbF7EjsXOHVAsmAtHTnhx4WKPKNuI3qEo5z0eAy50%3D&st=2018-03-05T19%3A42%3A59Z&se=2018-04-05T19%3A47%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by cmcclister** [comment]
#sign-off Production 1199282

**Comment by bennage** [comment]
@cmcclister Do we need to add this to all landing pages? We have multiple landing pages?
How is this used?

**Comment by cmcclister** [comment]
@bennage I was told that only https://docs.microsoft.com/en-us/azure/architecture/ needs this update.

**Comment by bennage** [comment]
Who can I talk to in order to find out more?

**Comment by cmcclister** [comment]
Hi @bennage , @sabarret would be able to clarify if this needs to be included on any other pages in this repo.

**Pull request merged**
