### PR TITLE
Update nva-ha.md

### PR DESCRIPTION
**Pull request by omartin2010**
Adding an alternate solution to multiple parallel NVAs. Let me know what you think, @telmosampaio :)

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/dmz/nva-ha.md](https://github.com/omartin2010/architecture-center/blob/patch-1/docs/reference-architectures/dmz/nva-ha.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha?branch=pr-en-us-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C5%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201704052014371860-32%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by omartin2010** [comment]
@telmosampaio , did you see the change?

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/dmz/nva-ha.md](https://github.com/omartin2010/architecture-center/blob/patch-1/docs/reference-architectures/dmz/nva-ha.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha?branch=pr-en-us-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C15%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201704150119339939-32%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by telmosampaio** [comment]
#sign-off

**Pull request merged**
