### PR TITLE
clarity edits for jenkins RA

### PR DESCRIPTION
**Pull request by bennage**
I'm not confident in how to word this.
I'm under the impression that there a single service principal that used by all of the agents.
Does the master use the service principal?

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/jenkins-security/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-420) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C21%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802210038031657-420%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XwMIhYzX%2FLDoZGYPrJmLXBYBY3XWz4Vw%2FNP%2FvjZrq04%3D&st=2018-02-21T00%3A34%3A16Z&se=2018-03-24T00%3A39%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/jenkins-security/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-420) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C21%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802210042348077-420%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=A7tfczYT5DEQ4JIKoQadTGXJ8JTru0V5KOXgEN%2BP%2BIM%3D&st=2018-02-21T00%3A38%3A34Z&se=2018-03-24T00%3A43%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lbrader** [comment]
The Master can be assigned a SP.  Each  Agent in the pipeline can also be setup with it's own SP to help separate different resources for security reasons.  Also this brings in the questions of how many Key - Vaults do you want to support in your pipeline.  1 or many.

**Comment by bennage** [comment]
I just discussed this with PC. She was okay with the change.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/jenkins-security/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-420) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C22%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802221737108484-420%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OymO7zTOaZZSta7WvWZbcFnd3K2oPid3OfKHejiMlj4%3D&st=2018-02-22T17%3A33%3A05Z&se=2018-03-25T17%3A38%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/jenkins-security/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-420) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802261759016576-420%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xW5MfQ%2Bep%2Bc16HozADd4qLmXQREmLBALWI4w9OBN6S4%3D&st=2018-02-26T17%3A54%3A56Z&se=2018-03-29T17%3A59%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
