### PR TITLE
Update hub-spoke.md

### PR DESCRIPTION
**Pull request by anavinahar**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/anavinahar/architecture-center/blob/patch-1/docs/reference-architectures/hybrid-networking/hub-spoke.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-402) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C13%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802132306491332-402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JMwYLpliBWhtHvYU7SU5KzQS8ClodN8R4PSqN0oFLbs%3D&st=2018-02-13T23%3A02%3A45Z&se=2018-03-16T23%3A07%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anavinahar** [comment]
#sign-off

**Comment by bennage** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/mspnp/architecture-center, working directory: W:\jm3z-s, target branch: master, target branch commit: 475064f0a3c2fac23e1286ba159aaded287eec86, source branch: b0ad0f538871006d9f63b4a93cb653b1/patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C16%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802161920558207-402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Vh2SrH8fxyoNvMEeZ5XLqsUHFBoM1eosxMntO90LBgc%3D&st=2018-02-16T19%3A16%3A05Z&se=2018-03-19T19%3A21%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/mspnp/architecture-center, working directory: W:\kut4-s, target branch: master, target branch commit: 475064f0a3c2fac23e1286ba159aaded287eec86, source branch: b0ad0f538871006d9f63b4a93cb653b1/patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C16%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802161921085066-402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Cj7LSUYLIR%2BP0uY4cdI9EHRXrM9v9oPqXpU7WAZZHW0%3D&st=2018-02-16T19%3A16%3A17Z&se=2018-03-19T19%3A21%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/anavinahar/architecture-center/blob/patch-1/docs/reference-architectures/hybrid-networking/hub-spoke.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?branch=pr-en-us-402) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C16%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802161921438598-402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=agaFGlSIRDXLzlyzJ4%2F06A4P0Xpbs9Eor26nf5oRvzg%3D&st=2018-02-16T19%3A17%3A42Z&se=2018-03-19T19%3A22%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by telmosampaio** [comment]
@anavinahar, I am confused now. I originally had that text in the document, that you could use gateways as a way to route between spokes. But I was told that was NOT supported by us. Are you saying we support that scenario?

**Comment by anavinahar** [comment]
Let's sync offline.

**Pull request closed without merging**
