### PR TITLE
Correcting data disk caching default

### PR DESCRIPTION
**Pull request by CHDAFNI-MSFT**
Data disks have caching set to none by default. OS is set to read/write

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/CHDAFNI-MSFT/architecture-center/blob/patch-1/docs/reference-architectures/identity/adds-extend-domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain?branch=pr-en-us-571) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C11%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806111343445377-571%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RqmXg37sFivjBHv9xhpoqwaZ3YbdPzrRigEBhi2Bank%3D&st=2018-06-11T13%3A39%3A53Z&se=2018-07-12T13%3A44%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
Hi, 

Based on [this doc](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching), the default cache setting for data disks is ReadOnly

**Comment by CHDAFNI-MSFT** [comment]
Per the reference architecture guide, standard disks are ‘None’, premium disks are ‘ReadOnly’… so I guess we are both right.

https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines


Specifies the caching requirements.

Possible values are:

None

ReadOnly

ReadWrite

Default: None for Standard storage. ReadOnly for Premium storage. - None, ReadOnly, ReadWrite



Chase Dafnis

Sr. Premier Field Engineer
US Public Sector
Microsoft Corporation

Office: 646.225.4724
Chase.Dafnis@microsoft.com<mailto:Chase.Dafnis@microsoft.com>

[Twitter]<https://twitter.com/Microsoft>    [Facebook] <https://www.facebook.com/Microsoft>     [Linkedin] <https://www.linkedin.com/company/microsoft>     [Youtube] <https://www.youtube.com/user/Microsoft>

[Microsoft Logo]

If you have any feedback about my work, please let either myself or my manager Arthur Dahl know at adahl@microsoft.com<mailto:adahl@microsoft.com>

**Comment by MikeWasson** [comment]
@CHDAFNI-MSFT  That makes sense - it's a little confusing with Premium vs Standard and OS vs data disks. However we recommend Premium so I think the reference architecture doc is correct as stands. Closing this issue.

**Pull request closed without merging**
