### PR TITLE
Additional scenario and approach for throttling

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by Court72** [comment]
@EdPrice-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by udidahan** [comment]
Hey folks, just wanted to make sure this wasn't being forgotten. Thanks :)

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
