### PR TITLE
Update sports-analytics-architecture-azure-content.md

### PR DESCRIPTION
**Pull request by jaswitze**
Removed the "Deploy this scenario" section to remove any confusion

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@jdmartinez36 - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger7** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by EdPrice-MSFT** [comment]
Checking with Jake and Guilia. Looks like Jake initiated this PR.

**Review by EdPrice-MSFT — APPROVED** [review]
Sounds good.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger8** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
