### PR TITLE
Peter/goverance

### PR DESCRIPTION
**Pull request by Petertaylor9999**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/overview.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/overview?branch=pr-en-us-566) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C8%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806082149153191-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uSNDv4GmZJyFYH8IIWNTrNKcb9XKsZxtq2M6aPueom4%3D&st=2018-06-08T21%3A45%3A18Z&se=2018-07-09T21%3A50%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/overview.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/overview?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C8%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806082213098937-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MWpRbuf8kYaHSE5v0c3bw2AR%2Bdy5f8qZ1cHl0jKmnJA%3D&st=2018-06-08T22%3A09%3A15Z&se=2018-07-09T22%3A14%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/overview.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/overview?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C8%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806082220023352-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dShFO7M2PbdEUSpqJ%2FeLbFqpS%2F5w9V5W1SRQb9ujegI%3D&st=2018-06-08T22%3A16%3A05Z&se=2018-07-09T22%3A21%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/adoption-intro/azure-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/azure-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/governance-explainer.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/governance-explainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-explainer?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/adoption-intro/overview.md](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/adoption-intro/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/overview?branch=pr-en-us-566) |
[docs/cloud-adoption-guide/toc.yml](https://github.com/mspnp/architecture-center/blob/peter/goverance/docs/cloud-adoption-guide/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/azure-explainer?branch=pr-en-us-566) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C8%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201806082227345993-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9ca6ZUkCbEZZ920ZDNC6mQvZdMNYEArhmwixrLOy9b8%3D&st=2018-06-08T22%3A23%3A38Z&se=2018-07-09T22%3A28%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Petertaylor9999** [comment]
@bennage the video tag in OPS isn't embedding videos from azure.microsoft.com properly. I've opened a but on OPS to get them to fix it: https://ceapex.visualstudio.com/SRE/_workitems?id=25043

**Comment by Petertaylor9999** [comment]
@bennage I need this PR merged before I can open the intermediate PR. It depends on the TOC.

**Pull request merged**
