### PR TITLE
pci index update

### PR DESCRIPTION
**Pull request by simorjay**
REvised the OMS configuration process in the documentation.,

### CODE REVIEW

**Comment by bennage** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/mspnp/architecture-center, working directory: W:\54qs-s, target branch: master, target branch commit: d04c7bf6486537746011aad9154a95087645d8b2, source branch: 3ac08931a565979e5699c54046ab1ea5/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201710061702451268-250%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qcR%2FxC%2FR82jAvTnkgwJYsS35IBZPDmmdvXVFTvQNVr4%3D&st=2017-10-06T16%3A57%3A56Z&se=2017-10-07T17%3A07%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/compliance/pci-dss/index.md](https://github.com/simorjay/architecture-center/blob/master/docs/compliance/pci-dss/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/compliance/pci-dss/index?branch=pr-en-us-250) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201710061703438905-250%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zj3H%2BAP%2FQeG5aEzUj%2FNfoP97oFdo6sf3vrebB0yxWtw%3D&st=2017-10-06T16%3A59%3A51Z&se=2017-10-07T17%3A09%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/compliance/pci-dss/index.md](https://github.com/simorjay/architecture-center/blob/master/docs/compliance/pci-dss/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/compliance/pci-dss/index?branch=pr-en-us-250) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C7%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201710071539152498-250%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bUZVTEazQXlMaHEEWTx7w0ZPXqX6SQNxlBdEeHl%2Fz8Y%3D&st=2017-10-07T15%3A35%3A13Z&se=2017-10-08T15%3A45%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
Changes incorporated into #251

**Pull request closed without merging**
