### PR TITLE
Address issue 457 from Holger Otto Andre about Availability - and fix Jenkins

### LINKED ISSUE #457: Jenkins clarity
Availability considerations
Assess the availability requirements for your workflow and how to recover the Jenkin state should the Jenkin server goes down.

What is the mean of the last line?? BTW there are many places where Jenkins is used instead of Jenkins

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c5ba03-a6ce-5d5c-fb83-e3e4e13da80d
* Version Independent ID: 6f235fae-19ab-9b12-72a9-f9962076ef5b
* Content: [Run a Jenkins server on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/#architecture)
* Content Source: [docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/jenkins/index.md)
* Service: **guidance**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

### PR DESCRIPTION
**Pull request by lbrader**
Fixes #457

### CODE REVIEW

**Comment by lbrader** [comment]
@MikeWasson Ready for review

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/larry/jenkins/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-515) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201804302251364275-515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fiPXmT1kASdJq%2BmEX776I5Y0NCJNYTubriixerfhkHY%3D&st=2018-04-30T22%3A47%3A47Z&se=2018-05-31T22%3A52%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/larry/jenkins/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-515) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201804302302442002-515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8idhnyQLEqeqtWObaIgnPDU1cwJqp3c9xR0KkYPvPWA%3D&st=2018-04-30T22%3A58%3A49Z&se=2018-05-31T23%3A03%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/larry/jenkins/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-515) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201804302305532473-515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IHEx3QCeCAEq%2FWI0WGx%2BSyWRlP8T7VKJbvnrWQhR1Pg%3D&st=2018-04-30T23%3A02%3A04Z&se=2018-05-31T23%3A07%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/larry/jenkins/docs/reference-architectures/jenkins/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index?branch=pr-en-us-515) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C30%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201804302306265002-515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=24nvIS48Msovd%2FA8ljYhqhVS1vvXam2Qrt9LrVMrgKo%3D&st=2018-04-30T23%3A03%3A07Z&se=2018-05-31T23%3A08%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
