### PR TITLE
cdn code snippets/samples added

### PR DESCRIPTION
**Pull request by woodp**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/woodp/architecture-center/blob/cdn-snippets/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-87) |
[docs/best-practices/images/cdn/rules-engine.png](https://github.com/woodp/architecture-center/blob/cdn-snippets/docs/best-practices/images/cdn/rules-engine.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-87) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C5%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201705051708438450-87%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by francischeung** [comment]
@woodp Could you please rebase and resolve conflicts?

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/woodp/architecture-center/blob/cdn-snippets/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-87) |
[docs/best-practices/images/cdn/rules-engine.png](https://github.com/woodp/architecture-center/blob/cdn-snippets/docs/best-practices/images/cdn/rules-engine.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-87) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C19%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201710191803297654-87%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qcuY9WZurFZP6wRijJYz0Ha2iqP3hCTDVil5gH0JVDA%3D&st=2017-10-19T17%3A59%3A55Z&se=2017-11-19T18%3A04%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/best-practices/cdn.md](https://github.com/woodp/architecture-center/blob/cdn-snippets/docs/best-practices/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-87) |
[docs/best-practices/images/cdn/rules-engine.png](https://github.com/woodp/architecture-center/blob/cdn-snippets/docs/best-practices/images/cdn/rules-engine.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/best-practices/cdn?branch=pr-en-us-87) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C19%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201710191804347087-87%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qb5FOizDrRx1OxRSrQLox9HAfn4fWMeVHHJRlPSuLpo%3D&st=2017-10-19T18%3A01%3A11Z&se=2017-11-19T18%3A06%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
