### PR TITLE
Update restrictions section

### PR DESCRIPTION
**Pull request by greg-lindsay**
rulesets can only be linked to virtual networks in the same region as the resolver

### CODE REVIEW

**Comment by greg-lindsay** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@moorthyannadurai 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by greg-lindsay** [comment]
@jak-ms if @moorthyannadurai doesn't respond, we need to merge this. The request to fix the content is from the main PM for DNS private resolver.

**Comment by moorthyannadurai** [comment]
#sign-off

**Comment by moorthyannadurai** [comment]
#sign-off

**Pull request merged**
