### PR TITLE
ACAG updates - subscriptions

### PR DESCRIPTION
**Pull request by alexbuckgit**

### CODE REVIEW

**Comment by bennage** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-controls?branch=pr-en-us-425) | [Details](#user-content-docs%2Fcloud-adoption-guide%2Fintermediate-stage%2Fsubscription-controls.md)
[docs/cloud-adoption-guide/intermediate-stage/automation.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/automation.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/enterprise-onboarding.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/enterprise-onboarding.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/enterprise-subscription.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/enterprise-subscription.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-intermediate.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-intermediate.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-multiple-original.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-multiple-original.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-multiple.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-multiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-multiple?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-ownership.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-ownership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-ownership?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-patterns.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-patterns.md) | :white_check_mark:Succeeded | |

<a name="docs%2Fcloud-adoption-guide%2Fintermediate-stage%2Fsubscription-controls.md"></a>
### [docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md)
 - **Line 11**: **[Warning]** Invalid file link:(~/cloud-adoption-guide/intermediate-stage/also known as quotas).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C23%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802232310597931-425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QL6dB5nlwRguKhKigBot5vYqGWJh2D80hmPtlzeB4Rc%3D&st=2018-02-23T23%3A07%3A07Z&se=2018-03-26T23%3A12%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/intermediate-stage/automation.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/automation.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/enterprise-onboarding.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/enterprise-onboarding.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/enterprise-subscription.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/enterprise-subscription.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-controls?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-intermediate.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-intermediate.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-multiple-original.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-multiple-original.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-multiple.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-multiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-multiple?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-ownership.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-ownership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-ownership?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-patterns.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-patterns.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C23%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802232314017716-425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=j7movf1lYvvO6OxX3tKmgBHd9zIcWtMt6C0wTlWi6NE%3D&st=2018-02-23T23%3A09%3A58Z&se=2018-03-26T23%3A14%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Petertaylor9999** [comment]
Hey Alex - could you please also add where you think these docs will go in the outline (overview.md)? This will help us figure out where these land in the "multiple teams/multiple projects" narrative.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cloud-adoption-guide/intermediate-stage/automation.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/automation.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/enterprise-onboarding.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/enterprise-onboarding.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/enterprise-subscription.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/enterprise-subscription.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/overview.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/overview?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-controls?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-intermediate.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-intermediate.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-multiple-original.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-multiple-original.md) | :white_check_mark:Succeeded | |
[docs/cloud-adoption-guide/intermediate-stage/subscription-multiple.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-multiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-multiple?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-ownership.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-ownership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/intermediate-stage/subscription-ownership?branch=pr-en-us-425) |
[docs/cloud-adoption-guide/intermediate-stage/subscription-patterns.md](https://github.com/mspnp/architecture-center/blob/alex-acag-intermediate-working/docs/cloud-adoption-guide/intermediate-stage/subscription-patterns.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201802261758586353-425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CaiOAy%2FA%2FXvZFM1IwnPpF4i8c71B48mVT9qfKwQgsHw%3D&st=2018-02-26T17%3A55%3A01Z&se=2018-03-29T18%3A00%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/mspnp/architecture-center, working directory: W:\lvng-s, target branch: acag-intermediate-working, target branch commit: 0e7f1d98c9ab0ce78234d978ec8ca3afb14d725a, source branch: alex-acag-intermediate-working, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C2%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201803020035263364-425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m5MHmF5dznQxBryTdgx19XT6KiEgVdCYUhAJ0ahyQVU%3D&st=2018-03-02T00%3A30%3A35Z&se=2018-04-02T00%3A35%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by alexbuckgit** [comment]
Closing PR due to validation errors. Will submit a new PR instead.

**Pull request closed without merging**
