### PR TITLE
Minor edit to add name to list of authors

### PR DESCRIPTION
**Pull request by msalvaris**

### CODE REVIEW

**Comment by MikeWasson** [comment]
@msalvaris There are no changes in this PR. If you're updating the 'author' metadata, the value should be a single GitHub alias, which should be the person who is responsible to make any content updates. thx!

**Comment by msalvaris** [comment]
@MikeWasson Thanks, I was simply following up on what Ed had said:
[11/12/18 10:55 PM] Ed Price
Mathew, would you mind opening a PR on it so we get your name listed as the author on the Ref Arch page? Mike Wasson, is this the best method? Thanks!

Have I misunderstood the instruction?

**Comment by MikeWasson** [comment]
It's the right process just the commits in this PR are empty (only whitespace changes)

**Comment by MikeWasson** [comment]
Superseded by #1171

**Pull request closed without merging**
