### PR TITLE
Add Azure Database for MySQL/PostgreSQL to index

### LINKED ISSUE #296: Azure Database for MySQL/Postgres not mentioned

### PR DESCRIPTION
**Pull request by gsacavdm**
Fixes #296

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/index.md](https://github.com/gsacavdm/architecture-center/blob/patch-4/docs/aws-professional/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/index?branch=pr-en-us-299) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C16%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201711160126554035-299%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UvXZkD32db6m7e%2BXUwZ0itZD2fxgeMk6hJ8fkfVILL8%3D&st=2017-11-16T01%3A23%3A03Z&se=2017-12-17T01%3A28%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lbrader** [comment]
@gsacavdm I'm going to throw this back to you.   Mike and I generally like the refactor except for 
refactoring "Azure SQL Database service"  to "Azure Database services".  

Concerns:
1.  There is no "Azure Database services" branding term OR is this a new term to use?
2. "Azure Database services" implies all the various DB services not just SQL

**Comment by gsacavdm** [comment]
Agree on the first concern, as for the second, that's what I was going for. RDS aligns with multiple different services in Azure. Any suggestions on how you'd like to see this?

I also toyed around with "*RDS, Azure SQL Database service, and Azure Database for MySQL/PostgreSQL*" but this won't scale as we add more managed DBs (like MariaDB which was just announced).

**Comment by MikeWasson** [comment]
@gsacavdm I think the issue is "database" would include Cosmos DB etc. 

RDS and Azure relational database services?

**Comment by gsacavdm** [comment]
@MikeWasson , I like that suggestion. I made the update.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/index.md](https://github.com/gsacavdm/architecture-center/blob/patch-4/docs/aws-professional/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/index?branch=pr-en-us-299) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C20%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201711200851066435-299%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xB2gDowEkExnFiy4Vnmv%2BPgMT8kyVZxReymYVE7tAoQ%3D&st=2017-11-20T08%3A47%3A02Z&se=2017-12-21T08%3A52%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
