### PR TITLE
Minor spelling fixes

### PR DESCRIPTION
**Pull request by teamtam**

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/microservices/api-design.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/api-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/api-design?branch=pr-en-us-322) |
[docs/microservices/ci-cd.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/ci-cd.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd?branch=pr-en-us-322) |
[docs/microservices/domain-analysis.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/domain-analysis.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/domain-analysis?branch=pr-en-us-322) |
[docs/microservices/index.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/index?branch=pr-en-us-322) |
[docs/microservices/ingestion-workflow.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/ingestion-workflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/ingestion-workflow?branch=pr-en-us-322) |
[docs/microservices/interservice-communication.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/interservice-communication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/interservice-communication?branch=pr-en-us-322) |
[docs/microservices/logging-monitoring.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/logging-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring?branch=pr-en-us-322) |
[docs/microservices/microservice-boundaries.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/microservice-boundaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/microservice-boundaries?branch=pr-en-us-322) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712120529087051-322%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0GsMXEqiJvALrd46XK8k%2Bn523iUTaGJYNQxwp%2ByZ2qY%3D&st=2017-12-12T05%3A25%3A08Z&se=2018-01-12T05%3A30%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/microservices/api-design.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/api-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/api-design?branch=pr-en-us-322) |
[docs/microservices/ci-cd.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/ci-cd.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd?branch=pr-en-us-322) |
[docs/microservices/index.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/index?branch=pr-en-us-322) |
[docs/microservices/ingestion-workflow.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/ingestion-workflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/ingestion-workflow?branch=pr-en-us-322) |
[docs/microservices/interservice-communication.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/interservice-communication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/interservice-communication?branch=pr-en-us-322) |
[docs/microservices/logging-monitoring.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/logging-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring?branch=pr-en-us-322) |
[docs/microservices/microservice-boundaries.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/microservice-boundaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/microservice-boundaries?branch=pr-en-us-322) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712121601222285-322%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dSYb5Fn%2BtiZ%2Buuijrkuo8kqpM0PjaqCCXSHD78GUpR4%3D&st=2017-12-12T15%3A57%3A20Z&se=2018-01-12T16%3A02%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/microservices/api-design.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/api-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/api-design?branch=pr-en-us-322) |
[docs/microservices/ci-cd.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/ci-cd.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd?branch=pr-en-us-322) |
[docs/microservices/index.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/index?branch=pr-en-us-322) |
[docs/microservices/ingestion-workflow.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/ingestion-workflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/ingestion-workflow?branch=pr-en-us-322) |
[docs/microservices/interservice-communication.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/interservice-communication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/interservice-communication?branch=pr-en-us-322) |
[docs/microservices/logging-monitoring.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/logging-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring?branch=pr-en-us-322) |
[docs/microservices/microservice-boundaries.md](https://github.com/teamtam/architecture-center/blob/master/docs/microservices/microservice-boundaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/microservices/microservice-boundaries?branch=pr-en-us-322) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712121602442626-322%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5YqPWqNoHGIlY6WxG7wXkIfgmpkGAMGC4XbuteLxAbo%3D&st=2017-12-12T15%3A58%3A37Z&se=2018-01-12T16%3A03%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
got catches thanks! 😸

**Pull request merged**
