### PR TITLE
Changes to IoT-related services

### PR DESCRIPTION
**Pull request by mollyhe1**
Updating info on existing services

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/services.md](https://github.com/mollyhe1/architecture-center/blob/patch-1/docs/aws-professional/services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/services?branch=pr-en-us-314) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C4%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201712040028420618-314%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jWod2jcSkf0fr%2FvqT96cAKLVYSX6fMxRuh%2BOK4ys%2FrQ%3D&st=2017-12-04T00%3A24%3A40Z&se=2018-01-04T00%3A29%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
Do we have official docs (not a blog post) to link to? @mollyhe1 @lbrader

**Comment by mollyhe1** [comment]
https://docs.microsoft.com/azure/iot-edge/tutorial-deploy-function

Thanks!


________________________________

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/services.md](https://github.com/mollyhe1/architecture-center/blob/patch-1/docs/aws-professional/services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/services?branch=pr-en-us-314) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C2%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801021807345130-314%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LV5DRlFisOD1jgY%2F6CtFYD3%2FzfnJL6ikHlhPDlbaTBY%3D&st=2018-01-02T18%3A03%3A47Z&se=2018-02-02T18%3A08%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
