### PR TITLE
Monitoring data solutions

### PR DESCRIPTION
**Pull request by joelhulen**
I originally wrote this article for the Azure Data Architecture Guide. It was not included in the released version because it was not data-centric enough. Hopefully these changes will suffice for refocusing the content. Reviewed by @EdPrice-MSFT

### CODE REVIEW

**Comment by bennage** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/data-guide/scenarios/monitoring-data-solutions.md](https://github.com/joelhulen/architecture-center/blob/monitoring-data-solutions/docs/data-guide/scenarios/monitoring-data-solutions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/monitoring-data-solutions?branch=pr-en-us-535) | [Details](#user-content-docs%2Fdata-guide%2Fscenarios%2Fmonitoring-data-solutions.md)
[docs/data-guide/scenarios/images/monitoring-products-overview.png](https://github.com/joelhulen/architecture-center/blob/monitoring-data-solutions/docs/data-guide/scenarios/images/monitoring-products-overview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/monitoring-data-solutions?branch=pr-en-us-535) |

<a name="docs%2Fdata-guide%2Fscenarios%2Fmonitoring-data-solutions.md"></a>
### [docs/data-guide/scenarios/monitoring-data-solutions.md](https://github.com/joelhulen/architecture-center/blob/monitoring-data-solutions/docs/data-guide/scenarios/monitoring-data-solutions.md)
 - **Line 22**: **[Warning]** Invalid file link:(~/data-guide/common-architectures/data-pipeline.md).
 - **Line 28**: **[Warning]** Invalid file link:(~/data-guide/pipeline-patterns/time-series.md).
 - **Line 28**: **[Warning]** Invalid file link:(~/data-guide/common-architectures/big-data.md).
 - **Line 115**: **[Warning]** Invalid file link:(~/data-guide/technology-choices/data-ingest.md).
 - **Line 121**: **[Warning]** Invalid file link:(~/data-guide/technology-choices/data-serving-storage.md).
 - **Line 122**: **[Warning]** Invalid file link:(~/data-guide/technology-choices/real-time-processing.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C16%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201805160341466877-535%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4kpKt9FZH2bNHoW6T9JWAQmRe5MoCndxGFAQuhzWAS8%3D&st=2018-05-16T03%3A37%3A54Z&se=2018-06-16T03%3A42%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by joelhulen** [comment]
Oops (broken links). Those were correct in my original environment where I authored the ADAG. After moving the files to the new repo, the folder structure was changed. I'll fix.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/data-guide/scenarios/images/monitoring-products-overview.png](https://github.com/joelhulen/architecture-center/blob/monitoring-data-solutions/docs/data-guide/scenarios/images/monitoring-products-overview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/monitoring-data-solutions?branch=pr-en-us-535) |
[docs/data-guide/scenarios/monitoring-data-solutions.md](https://github.com/joelhulen/architecture-center/blob/monitoring-data-solutions/docs/data-guide/scenarios/monitoring-data-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/monitoring-data-solutions?branch=pr-en-us-535) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C16%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201805160443191670-535%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Kit%2FMlpwDNFs38hc3of8H4sPewSJqiW6n%2BOZhkS69AE%3D&st=2018-05-16T04%3A39%3A23Z&se=2018-06-16T04%3A44%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MikeWasson** [comment]
Thanks @joelhulen ! I'll review this.

**Comment by tomkerkhove** [comment]
@MikeWasson Any thoughts on this? Let us know if there are some missing pieces or the wording is not correct.

**Comment by joelhulen** [comment]
@MikeWasson Just following up on this to see if you need any additional information or modifications. Thanks!

**Comment by MikeWasson** [comment]
@joelhulen Hey - First, sorry that it's taken me so long to review this.

I feel this topic is still very high-level and doesn't get much into the specifics of data solutions. 

- What specific metrics should you look at in data architectures?
- Differences in monitoring stream processing vs batch processing vs OLTP workloads? 
- Considerations for monitoring specific technology stacks like DataBricks
- Considerations for creating a monitoring dashboard
- Correlation tracing

I'm thinking that to do this topic justice would take more than one overview. At the same time time, there isn't really a technology matrix to include, as there is for the other data technologies. The high-level overview of monitoring services in Azure is useful but largely duplicates the [Azure Monitor overview](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview). 

I hate to squash a topic that you wrote but I do think it needs more depth, and at this point I'd rather wait until we can produce a more actionable set of monitoring/performance analysis guidance.

**Pull request closed without merging**
