### PR TITLE
AWS service map: Updates to microservice-related services

### PR DESCRIPTION
**Pull request by MikeWasson**
Fixes https://github.com/mspnp/architecture-center/issues/349

- Add Amazon EKS and Azure AKS
- Add Azure ACI
- Reorganize "microservices" category
- Move WebJobs to "compute" section
- Move Quickstart Templates to "developer tools" section
- Remove duplicate entries for Logic Apps enterprise integration features

### CODE REVIEW

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/mike/azure-for-aws/docs/aws-professional/services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/services?branch=pr-en-us-352) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C5%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801051822151706-352%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e1%2BJoJAK42lMv2Y9u8tOQQuG2HamIb3ts21lGxvxhQc%3D&st=2018-01-05T18%3A18%3A41Z&se=2018-02-05T18%3A23%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/mike/azure-for-aws/docs/aws-professional/services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/services?branch=pr-en-us-352) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C5%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801051829035188-352%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yVjDHKMMYRQpepZwvWngkL9IjJHB4GFyK6Y9es3qGOU%3D&st=2018-01-05T18%3A25%3A14Z&se=2018-02-05T18%3A30%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bennage** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/mike/azure-for-aws/docs/aws-professional/services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/azure/architecture/aws-professional/services?branch=pr-en-us-352) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C5%5C0659c0de-90b3-6253-8249-f3f6e8fba551%5CPullRequest%5C201801051830043711-352%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6VcgZGUggvEJEklXX%2BnYV0SNju4QFoeenMcx85lADJQ%3D&st=2018-01-05T18%3A26%3A36Z&se=2018-02-05T18%3A31%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lbrader** [comment]
Reviewed and looks good - thanks Mike

**Pull request merged**
